### ISSUE TITLE
clistpacket bug

### ISSUE THREAD

**Issue by erwan-joly** [NosCoreIO/NosCore.Packets#95]
https://github.com/NosCoreIO/NosCore.Packets/pull/94

**Comment by GorlikItsMe** [comment]
Example packet
`clist 0 charName 0 1 0 9 0 0 1 0 -1.12.1.8.-1.-1.-1.-1.-1.-1 1  1 1 -1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1. 0 0`

**Comment by erwan-joly** [comment]
are you totally sure clist packet has an extra . ?`-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.`

**Comment by GorlikItsMe** [comment]
I copy this packet 2 days ago.
Today i check it again for you
`clist 0 mycharname 0 1 0 2 0 0 1 0 -1.12.1.8.-1.-1.-1.-1.-1.-1 1  1 1 -1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1.-1. 0 0`
its that character without pets
https://i.imgur.com/e0xfjZx.png

**Comment by 0Lucifer0** [comment]
Perfect a bit surprising but that should work fine now
